/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  AccessTokens: () => import('#controllers/access_tokens_controller'),
  Categories: () => import('#controllers/categories_controller'),
  Config: () => import('#controllers/config_controller'),
  Editions: () => import('#controllers/editions_controller'),
  Items: () => import('#controllers/items_controller'),
  Links: () => import('#controllers/links_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  Persona: () => import('#controllers/persona_controller'),
  Profile: () => import('#controllers/profile_controller'),
  Quiz: () => import('#controllers/quiz_controller'),
  RunDaily: () => import('#controllers/run_daily_controller'),
  Sources: () => import('#controllers/sources_controller'),
}
